version: '3.8'

services:
  db:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    container_name: node-todo-app
    ports:
      - "9000:3000"
    environment:
      PORT: 3000
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
      DB_PORT: 5432
    depends_on:
      - db